apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-{{ .Values.frontend.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.prefix }}-{{ .Values.frontend.name }}
