apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-{{ .Values.frontend.name }}-configmap
data:
  config.js: |
    var config = (() => {
      return {
        "SERVER_URL": "http://{{ .Values.ingress.host }}:{{ .Values.backend.service.port }}",
      };
    })();
