{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.prefix }}-{{ .Chart.Name }}
  labels:
    chart: {{ .Values.prefix }}-{{ .Chart.Name }}-{{ .Chart.Version }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- if eq .Values.ingress.environment "rws" }}
  - host: {{ .Values.ingress.host }}
    http:
  {{- else if eq .Values.ingress.environment "google"}}
  - http:
  {{- end}}
      paths:
      {{- range .Values.ingress.services}}
      - path: {{ .path }}
        backend:
          serviceName: {{ $.Values.prefix }}-{{ .name }}
          servicePort: {{ .port }}
      {{- end }}
{{- end }}
